
tasks:
# even though will be updated by starting the default build task in in tasks.json for docker >=20 (--pull always),
# having the image inside the workspace already saves time when building for the first time in a new gitpod
  - init: docker pull $(cat .vscode/settings.json | python3 -c "import json, sys; print(json.load(sys.stdin)['vorlage-latex.buildcontainer'])")
    command: exit
  - command: docker run -d --name nginx-pdf --restart=always -v "$GITPOD_REPO_ROOT/Latex:/usr/share/nginx/html:ro" -p 12345:80 nginx

vscode:
# remember to update these together with .vscode/extensions.json
  extensions:
    - anweber.statusbar-commands
    - aaron-bond.better-comments
    - CoenraadS.bracket-pair-colorizer
# latex workshop 8.20.2 on openvsx (released on august 24th) has a weird bug where the enter key stops working
# https://github.com/James-Yu/LaTeX-Workshop/issues/2845
    - James-Yu.latex-workshop@8.19.2

github:
  prebuilds:
# enable for the master/default branch (defaults to true)
    master: true
# enable for all branches in this repo (defaults to false)
    branches: true
# enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
# enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
# add a check to pull requests (defaults to true)
    addCheck: true
# add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
# add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
# add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: false
